channels:
  - conda-forge
dependencies:
  - python=3.11
  - huggingface_hub=0.26.5
  - matplotlib=3.10.0
  - numpy=2.2.1
  - pip
  - pip:
    - anemoi_inference==0.3.3
    - anemoi_models==0.2.1
    - anemoi_transform==0.1.0
    - anemoi_utils==0.4.9
    - earthkit_data==0.11.4
    - earthkit_geo==0.3.0
    - earthkit_meteo==0.3.0
    - earthkit_regrid==0.3.4
    - Cartopy==0.24.1
    - ecmwf_opendata==0.3.14
