{% set name = "lfric-gpl-utils" %}
{% set version = "2.0.0" %}
{% set revision = "44185" %}

package:
    name: {{name|lower}}
    version: {{version}}.{{revision}}

source:
    svn_url: {{ environ.get('NGMOENVS_MOSRS_MIRROR', 'https://code.metoffice.gov.uk/svn') }}/lfric/GPL-utilities/tags/v{{version}}
    svn_rev: {{revision}}

build:
    number: 0
    noarch: python

requirements:
  #    build:
  #        - subversion
    host:
        - python
        - setuptools

test:
    imports:
        - rose_lfric.config
        - rose_picker.rose_picker
    commands:
        - rose_picker --help

about:
    home: https://code.metoffice.gov.uk/trac/lfric
    license: GPL3
    license_file: COPYING
    summary: LFRic utilities


