{% set name = "psyclone" %}
{% set version = "3.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/stfc/PSyclone/archive/refs/tags/v{{version}}.tar.gz
  sha256: 6ad57863644375c60b875da3c4ad0a9986a74af513f808f52a6c6aeadeb4b295

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - configparser
    - fparser
    - jsonschema
    - pip
    - pyparsing
    - python
    - six
    - sympy
  run:
    - configparser
    - fparser >=0.2.0
    - jsonschema
    - pyparsing
    - python
    - six
    - sympy
    - python-graphviz
    - jinja2
    - termcolor

test:
  imports:
    - psyclone

about:
  home: "https://github.com/stfc/psyclone"
  license: "OSI Approved :: BSD 3-Clause"
  license_family: BSD
  license_file: 
  summary: "PSyclone - a compiler for Finite Element/Volume/Difference DSLs in Fortran"
  doc_url: 
  dev_url: 


