channels:
  - conda-forge
  - local
dependencies:
  - python=3.10
  - psyclone
  - lfric-gpl-utils=2
  - jinja2
  - sci-fab
  - python-clang
  - libsqlite <3.49 # Allow double quotes for dependency generator
