#!/bin/bash

ENV_DIR=$( cd -- "$( dirname -- "$(readlink -f "${BASH_SOURCE[0]}")" )" &> /dev/null && pwd )/..

# Arguments to apptainer
export MOUNT_ARGS=(
    "--bind" "/opt/AMD" # AOCC compiler
    "--bind" "/usr/lib64:/host/lib64" # System libraries
    "--bind" "/run/user/$UID" # Sockets
)

# Used by srun on the queue
if [[ -d /var/spool/slurmd ]]; then
    MOUNT_ARGS+=(--bind /var/spool/slurmd)
fi

module load "singularity/4.1.0-slurm"

singularity run "${MOUNT_ARGS[@]}" "$ENV_DIR/etc/image.sif" "$@"
