#!/bin/bash

ENV_DIR=$( cd -- "$( dirname -- "$(readlink -f "${BASH_SOURCE[0]}")" )" &> /dev/null && pwd )/..

# Make Gadi's system libraries available in the container
MOUNT_ARGS=(--bind /lib64:/system/lib64 --bind /lib:/system/lib --bind /half-root --bind /opt/pbs --bind /sys/fs/cgroup)

# Used by mpirun on the queue
if [[ -d /local/spool ]]; then
    MOUNT_ARGS+=(--bind /local/spool)
fi

# Local FCM keyword file
export FCM_KEYWORDS=/g/data/hr22/apps/etc/fcm/mosrs/keyword.cfg

# Add central OpenMPI to cflags
export FFLAGS="-I /apps/openmpi/4.1.5/include/Intel ${FFLAGS:-}"

# Pass through LD_LIBRARY_PATH
export SINGULARITYENV_LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}"

/opt/singularity/bin/singularity run "${MOUNT_ARGS[@]}" "$ENV_DIR/etc/apptainer.sif" "$@"
