#!/bin/bash

ENV_DIR=$( cd -- "$( dirname -- "$(readlink -f "${BASH_SOURCE[0]}")" )" &> /dev/null && pwd )/..

# Make Gadi's system libraries available in the container
MOUNT_ARGS=(--bind /lib64:/system/lib64 --bind /lib:/system/lib --bind /half-root --bind /opt/pbs --bind /sys/fs/cgroup)

# Used by mpirun on the queue
if [[ -d /local/spool ]]; then
    MOUNT_ARGS+=(--bind /local/spool)
fi

# Local FCM keyword file
export FCM_KEYWORDS=/g/data/hr22/apps/etc/fcm/mosrs/keyword.cfg

# Add central OpenMPI to cflags
export FFLAGS="-I /apps/openmpi/4.1.5/include/Intel ${FFLAGS:-}"

# Pass through LD_LIBRARY_PATH
export SINGULARITYENV_LD_LIBRARY_PATH="/.singularity.d/libs:${LD_LIBRARY_PATH:-}"

# Remove the wrapper dir from path
NGMOENVS_CLEAN_PATH=$(tr ':' '\n' <<< "$PATH" | xargs readlink -f | uniq | grep -v $(readlink -f "$ENV_DIR/bin") | paste -sd ':')

# Required for oneapi sanitizers to show addresses
export SINGULARITYENV_APPEND_PATH="$NGMOENVS_CLEAN_PATH:/apps/intel-tools/intel-compiler-llvm/2025.0.4/bin/compiler"

/opt/singularity/bin/singularity run "${MOUNT_ARGS[@]}" "$ENV_DIR/etc/apptainer.sif" "$@"
